apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellodeployment
spec:
  selector:
    matchLabels:
      app: helloapp
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: helloapp
    spec:
      containers:
      - name: hello
        image: <ACR login server>/helloworld:2.0

---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: helloapp